#This file will defines output of each components
#Here the enities are the components of training pipeline

class DataIngestionArtifact:...
class DataValidationArtifact:...
class DataTransformationArtifact:...
class ModelTrainerArtifact:...
class ModelEvaluationArtifact:...
class ModelPusherArtifact:...