#This file will defines input for each components
#Here the enities are the components of training pipeline

class DataIngestionConfig:...
class DataValidationConfig:...
class DataTransformationConfig:...
class ModelTrainerConfig:...
class ModelEvaluationConfig:...
class ModelPusherConfig:...